/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as FeedAdminRouteImport } from './routes/feed.admin'
import { Route as ContentIdRouteImport } from './routes/content.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedAdminRoute = FeedAdminRouteImport.update({
  id: '/feed/admin',
  path: '/feed/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/prayers': typeof PrayersRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/videos': typeof VideosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/content/$id': typeof ContentIdRoute
  '/feed/admin': typeof FeedAdminRoute
  '/u/$handle': typeof UHandleRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/prayers': typeof PrayersRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/videos': typeof VideosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/content/$id': typeof ContentIdRoute
  '/feed/admin': typeof FeedAdminRoute
  '/u/$handle': typeof UHandleRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/prayers': typeof PrayersRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/videos': typeof VideosRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/content/$id': typeof ContentIdRoute
  '/feed/admin': typeof FeedAdminRoute
  '/u/$handle': typeof UHandleRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/auth'
    | '/create'
    | '/gallery'
    | '/home'
    | '/library'
    | '/more'
    | '/prayers'
    | '/profile'
    | '/saved'
    | '/videos'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/upload'
    | '/admin/users'
    | '/chat/$id'
    | '/content/$id'
    | '/feed/admin'
    | '/u/$handle'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/attendance'
    | '/auth'
    | '/create'
    | '/gallery'
    | '/home'
    | '/library'
    | '/more'
    | '/prayers'
    | '/profile'
    | '/saved'
    | '/videos'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/upload'
    | '/admin/users'
    | '/chat/$id'
    | '/content/$id'
    | '/feed/admin'
    | '/u/$handle'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendance'
    | '/auth'
    | '/create'
    | '/gallery'
    | '/home'
    | '/library'
    | '/more'
    | '/prayers'
    | '/profile'
    | '/saved'
    | '/videos'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/upload'
    | '/admin/users'
    | '/chat/$id'
    | '/content/$id'
    | '/feed/admin'
    | '/u/$handle'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  GalleryRoute: typeof GalleryRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  MoreRoute: typeof MoreRoute
  PrayersRoute: typeof PrayersRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  VideosRoute: typeof VideosRoute
  ChatIdRoute: typeof ChatIdRoute
  ContentIdRoute: typeof ContentIdRoute
  FeedAdminRoute: typeof FeedAdminRoute
  UHandleRoute: typeof UHandleRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/admin': {
      id: '/feed/admin'
      path: '/feed/admin'
      fullPath: '/feed/admin'
      preLoaderRoute: typeof FeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  GalleryRoute: GalleryRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  MoreRoute: MoreRoute,
  PrayersRoute: PrayersRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  VideosRoute: VideosRoute,
  ChatIdRoute: ChatIdRoute,
  ContentIdRoute: ContentIdRoute,
  FeedAdminRoute: FeedAdminRoute,
  UHandleRoute: UHandleRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
